"""Batched Qwen2.5-VL reranker for V2 Stage 2 inference on Kaggle GPU.

Implements three critical fixes over the V1 VLMService design:
- **Fix 2**: Structured JSON output with granular relevance scoring (not binary).
- **Fix 3**: Native PyTorch tensor batching via ``processor(images=..., text=...,
  padding=True)`` and a single ``model.generate()`` call per mini-batch.
- **Path safety**: Consumes explicit ``image_path`` from V1 ``SearchCandidate``,
  never reconstructs paths from ``frame_id``.

Designed for synchronous Kaggle/Colab execution (no async).  The existing
``VLMService`` in ``vlm_service.py`` remains unchanged for FastAPI compatibility.
"""

from __future__ import annotations

import contextlib
import gc
import json
import re
import textwrap
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from backend.core.logging import setup_logger

logger = setup_logger("v2_vlm_reranker")

# ---------------------------------------------------------------------------
# Structured prompt template (Fix 2)
# ---------------------------------------------------------------------------

_RELEVANCE_PROMPT: str = textwrap.dedent("""\
    You are an expert visual analyst for a video retrieval competition.
    Given the keyframe image and the search query below, evaluate how
    relevant this image is to the query.

    Query: {query}

    Respond with ONLY a valid JSON object in this exact format (no markdown):
    {{"relevance_score": <float 0.0 to 1.0>, "confidence": <int 1 to 5>, "answer": "<concise answer to the query>", "reasoning": "<one sentence justification>"}}""")


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class M2ScoredCandidate:
    """Single candidate after M2 VLM scoring."""

    rank: int
    video_id: str
    frame_id: int
    keyframe_id: str
    image_path: Path
    retrieval_score: float
    vlm_relevance: float   # continuous [0.0, 1.0]
    vlm_confidence: int    # 1-5 Likert scale
    vlm_answer: str
    vlm_reasoning: str


# ---------------------------------------------------------------------------
# JSON response parser (Fix 2: robust extraction with fallback)
# ---------------------------------------------------------------------------


def parse_vlm_json_response(raw_text: str) -> dict[str, Any]:
    """Extract structured fields from VLM output with multi-level fallback.

    Parsing priority:
    1. Direct JSON parse of the full output.
    2. Extract JSON from markdown code fences (```json ... ```).
    3. Extract the first ``{...}`` block via regex.
    4. Line-level key-value extraction (SCORE: 0.8 etc.).
    5. Return safe defaults so the pipeline never raises.

    Args:
        raw_text: Raw string generated by Qwen2.5-VL.

    Returns:
        Dict with keys ``relevance_score``, ``confidence``, ``answer``,
        ``reasoning``.  All values are guaranteed present and type-safe.
    """
    defaults: dict[str, Any] = {
        "relevance_score": 0.5,
        "confidence": 3,
        "answer": "",
        "reasoning": raw_text.strip()[:200] if raw_text else "",
    }

    if not raw_text or not raw_text.strip():
        return defaults

    # Strategy 1: direct parse
    parsed = _try_json_parse(raw_text.strip())
    if parsed is not None:
        return _validate_fields(parsed, defaults)

    # Strategy 2: markdown code fence
    fence_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw_text, re.DOTALL)
    if fence_match:
        parsed = _try_json_parse(fence_match.group(1))
        if parsed is not None:
            return _validate_fields(parsed, defaults)

    # Strategy 3: first brace-delimited block
    brace_match = re.search(r"\{[^{}]*\}", raw_text, re.DOTALL)
    if brace_match:
        parsed = _try_json_parse(brace_match.group(0))
        if parsed is not None:
            return _validate_fields(parsed, defaults)

    # Strategy 4: line-level key-value
    result = dict(defaults)
    lines = {
        line.split(":", 1)[0].strip().upper(): line.split(":", 1)[1].strip()
        for line in raw_text.splitlines()
        if ":" in line
    }
    if "SCORE" in lines or "RELEVANCE_SCORE" in lines:
        raw_score = lines.get("RELEVANCE_SCORE", lines.get("SCORE", ""))
        with contextlib.suppress(ValueError):
            result["relevance_score"] = max(0.0, min(1.0, float(raw_score)))
    if "ANSWER" in lines:
        result["answer"] = lines["ANSWER"]
    if "REASONING" in lines:
        result["reasoning"] = lines["REASONING"]
    if "RELEVANT" in lines and lines["RELEVANT"].upper() == "NO":
        result["relevance_score"] = max(0.0, result["relevance_score"] - 0.3)

    return result


def _try_json_parse(text: str) -> dict[str, Any] | None:
    try:
        obj = json.loads(text)
        if isinstance(obj, dict):
            return obj
    except (json.JSONDecodeError, ValueError):
        pass
    return None


def _validate_fields(parsed: dict[str, Any], defaults: dict[str, Any]) -> dict[str, Any]:
    result = dict(defaults)
    if "relevance_score" in parsed:
        with contextlib.suppress(TypeError, ValueError):
            result["relevance_score"] = max(0.0, min(1.0, float(parsed["relevance_score"])))
    if "confidence" in parsed:
        with contextlib.suppress(TypeError, ValueError):
            result["confidence"] = max(1, min(5, int(parsed["confidence"])))
    if "answer" in parsed and isinstance(parsed["answer"], str):
        result["answer"] = parsed["answer"].strip()
    if "reasoning" in parsed and isinstance(parsed["reasoning"], str):
        result["reasoning"] = parsed["reasoning"].strip()
    return result


# ---------------------------------------------------------------------------
# Image I/O helper
# ---------------------------------------------------------------------------


def _load_pil_image(path: Path) -> Any | None:
    """Load a keyframe as PIL RGB. Returns None on failure."""
    if not path.is_file():
        logger.warning("[M2] Keyframe not found: %s", path)
        return None
    try:
        from PIL import Image
        return Image.open(path).convert("RGB")
    except Exception as exc:  # noqa: BLE001
        logger.warning("[M2] Cannot read keyframe %s: %s", path, exc)
        return None


def _prefetch_images(paths: list[Path], max_workers: int = 4) -> list[Any | None]:
    """Prefetch images with thread-pool I/O overlap."""
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        return list(pool.map(_load_pil_image, paths))


# ---------------------------------------------------------------------------
# Batched VLM Reranker (Fix 3)
# ---------------------------------------------------------------------------


class M2BatchReranker:
    """Synchronous batched Qwen2.5-VL reranker for Kaggle GPU inference.

    Unlike the async ``VLMService``, this class:
    - Uses native PyTorch tensor batching (Fix 3).
    - Emits structured JSON scores (Fix 2).
    - Is synchronous (no ``async/await``).
    - Accepts explicit ``image_path`` from V1 candidates.

    Example::

        reranker = M2BatchReranker(device="cuda", use_4bit=True)
        reranker.load_model()
        scored = reranker.rerank(query, candidates, batch_size=4)
        reranker.unload_model()
    """

    def __init__(
        self,
        model_id: str = "Qwen/Qwen2.5-VL-7B-Instruct",
        device: str = "cuda",
        use_4bit: bool = True,
        max_new_tokens: int = 256,
    ) -> None:
        self._model_id = model_id
        self._device = device
        self._use_4bit = use_4bit
        self._max_new_tokens = max_new_tokens
        self._processor: Any | None = None
        self._model: Any | None = None
        self._is_loaded: bool = False

    @property
    def is_loaded(self) -> bool:
        return self._is_loaded

    # ── Lifecycle ─────────────────────────────────────────────────────

    def load_model(self) -> None:
        """Load Qwen2.5-VL with optional 4-bit quantization."""
        if self._is_loaded:
            return

        import torch
        from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

        if self._device == "cuda" and not torch.cuda.is_available():
            logger.warning("[M2] CUDA unavailable — falling back to CPU.")
            self._device = "cpu"

        logger.info("[M2] Loading %s on %s (4bit=%s)…", self._model_id, self._device, self._use_4bit)

        self._processor = AutoProcessor.from_pretrained(self._model_id, trust_remote_code=True)

        load_kwargs: dict[str, Any] = {"trust_remote_code": True}
        if self._device == "cuda" and self._use_4bit:
            from transformers import BitsAndBytesConfig
            load_kwargs["quantization_config"] = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.bfloat16,
            )
            load_kwargs["device_map"] = "auto"
        else:
            load_kwargs["torch_dtype"] = "auto"

        model = Qwen2_5_VLForConditionalGeneration.from_pretrained(self._model_id, **load_kwargs)
        if "device_map" not in load_kwargs:
            model = model.to(self._device)
        model.eval()

        self._model = model
        self._is_loaded = True
        logger.info("[M2] Model loaded successfully.")

    def unload_model(self) -> None:
        """Release model weights and VRAM."""
        if not self._is_loaded:
            return
        del self._model, self._processor
        self._model = self._processor = None
        self._is_loaded = False
        try:
            import torch
            torch.cuda.empty_cache()
        except (ImportError, RuntimeError):
            pass
        gc.collect()
        logger.info("[M2] Model unloaded.")

    # ── Core batched reranking ────────────────────────────────────────

    def rerank(
        self,
        query: str,
        candidates: list[Any],
        *,
        top_n: int = 30,
        batch_size: int = 4,
    ) -> list[M2ScoredCandidate]:
        """Rerank candidates using batched VLM inference.

        Args:
            query: Search query text.
            candidates: V1 ``SearchCandidate`` or ``FusedSearchCandidate`` list.
                Each must have ``.image_path``, ``.video_id``, ``.frame_id``,
                ``.keyframe_id``, and a score attribute.
            top_n: Number of top candidates to process through the VLM.
            batch_size: Images per forward pass (4-8 for T4 16 GB).

        Returns:
            Scored candidates ordered by original rank.
        """
        if not self._is_loaded:
            raise RuntimeError("Model not loaded. Call load_model() first.")

        import torch

        work = candidates[:top_n]
        results: list[M2ScoredCandidate] = []

        for batch_start in range(0, len(work), batch_size):
            batch = work[batch_start : batch_start + batch_size]
            paths = [Path(c.image_path) for c in batch]
            images = _prefetch_images(paths)

            # Separate valid (have image) vs invalid (missing image)
            valid_indices: list[int] = []
            valid_images: list[Any] = []
            for i, img in enumerate(images):
                if img is not None:
                    valid_indices.append(i)
                    valid_images.append(img)

            # Run batched inference for valid images
            vlm_outputs: dict[int, dict[str, Any]] = {}
            if valid_images:
                raw_texts = self._batched_generate(query, valid_images)
                for local_idx, raw in zip(valid_indices, raw_texts, strict=True):
                    vlm_outputs[local_idx] = parse_vlm_json_response(raw)

            # Assemble results for this mini-batch
            for i, c in enumerate(batch):
                score_attr = getattr(c, "rrf_score", None) or getattr(c, "score", 0.0)
                parsed = vlm_outputs.get(i, {
                    "relevance_score": 0.0,
                    "confidence": 1,
                    "answer": "",
                    "reasoning": "image not found",
                })
                results.append(M2ScoredCandidate(
                    rank=c.rank,
                    video_id=c.video_id,
                    frame_id=c.frame_id,
                    keyframe_id=c.keyframe_id,
                    image_path=Path(c.image_path),
                    retrieval_score=float(score_attr),
                    vlm_relevance=float(parsed["relevance_score"]),
                    vlm_confidence=int(parsed["confidence"]),
                    vlm_answer=str(parsed["answer"]),
                    vlm_reasoning=str(parsed["reasoning"]),
                ))

            # Inter-batch VRAM cleanup
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        # Append un-processed tail candidates with zero VLM signal
        for c in candidates[top_n:]:
            score_attr = getattr(c, "rrf_score", None) or getattr(c, "score", 0.0)
            results.append(M2ScoredCandidate(
                rank=c.rank,
                video_id=c.video_id,
                frame_id=c.frame_id,
                keyframe_id=c.keyframe_id,
                image_path=Path(c.image_path),
                retrieval_score=float(score_attr),
                vlm_relevance=0.0,
                vlm_confidence=1,
                vlm_answer="",
                vlm_reasoning="below top_n cutoff",
            ))

        return results

    def _batched_generate(self, query: str, images: list[Any]) -> list[str]:
        """Run a single batched forward pass over multiple images.

        Constructs per-image chat messages, applies the chat template,
        tokenizes with padding, and calls ``model.generate()`` once.

        Args:
            query: The search query.
            images: List of PIL.Image.Image (all valid, pre-loaded).

        Returns:
            List of raw generated strings, one per image.
        """
        import torch

        prompt_text = _RELEVANCE_PROMPT.format(query=query)

        # Build per-sample chat messages
        messages_batch = [
            [{"role": "user", "content": [
                {"type": "image", "image": img},
                {"type": "text", "text": prompt_text},
            ]}]
            for img in images
        ]

        # Apply chat template to each sample
        texts = [
            self._processor.apply_chat_template(
                msgs, tokenize=False, add_generation_prompt=True,
            )
            for msgs in messages_batch
        ]

        # Tokenize and batch with padding (Fix 3: true tensor batching)
        inputs = self._processor(
            text=texts,
            images=images,
            return_tensors="pt",
            padding=True,
        ).to(self._model.device if hasattr(self._model, "device") else self._device)

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=self._max_new_tokens,
            )

        # Strip input tokens from each output sequence
        try:
            input_len = inputs["input_ids"].shape[1]
            generated_ids = [seq[input_len:] for seq in output_ids]
        except (KeyError, AttributeError):
            generated_ids = output_ids

        decoded = self._processor.batch_decode(
            generated_ids,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )
        return [d.strip() for d in decoded]
