"""
Qwen2.5-VL Visual Language Model Service.

Implements Stage 3 of the cascading retrieval pipeline:

    Grounding DINO reranker (reranker.py)
    → [THIS MODULE] Qwen2.5-VL — VQA + System 2 CoT reasoning, Top-5

Two public methods are exposed:

* ``extract_vqa_answer`` — single-image inference; extracts a text answer
  for a VQA query from the top-ranked candidate.
* ``deep_reason`` — System 2 reasoning over the top-k candidates; re-scores
  each one based on VLM relevance judgment and populates ``reasoning_trace``.

**VRAM contract (8 GB budget):**
- Grounding DINO base ≈ 1.8 GB (loaded at startup).
- Qwen2.5-VL-7B-Instruct ≈ 15 GB in bf16 (too large for 8 GB alone).
- In production use 4-bit quantization (bitsandbytes) to reach ≈ 4.5 GB,
  leaving headroom for activations and the SigLIP 2 encoder.
- The model is loaded **on first use** (not at startup) and can be unloaded
  explicitly between request bursts via :meth:`unload_model`.
- When the model is absent the service falls back to empty answers/scores
  so the pipeline remains functional in CPU-only CI environments.
"""

from __future__ import annotations

import contextlib
import textwrap
from pathlib import Path

from backend.core.exceptions import ModelNotLoadedError, VRAMOverflowError
from backend.core.logging import setup_logger
from backend.schemas.rerank import RerankResultItem

logger = setup_logger("vlm_service")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_VQA_PROMPT_TEMPLATE: str = textwrap.dedent(
    """\
    You are an expert visual analyst assisting with a video retrieval task.
    Given the keyframe image and the search query below, provide a concise,
    accurate answer. If the query cannot be answered from the image alone,
    respond with "Cannot determine from image."

    Query: {query}
    Answer:"""
)

_REASONING_PROMPT_TEMPLATE: str = textwrap.dedent(
    """\
    You are performing deep visual reasoning for a video retrieval task.
    Given the keyframe image and search query, determine:
    1. Whether the image is relevant to the query (YES/NO).
    2. A relevance score between 0.0 and 1.0.
    3. A brief chain-of-thought explanation (1–2 sentences).

    Format your response EXACTLY as:
    RELEVANT: <YES|NO>
    SCORE: <float>
    REASONING: <explanation>

    Query: {query}"""
)

# Approximate VRAM footprint for Qwen2.5-VL-7B-Instruct at 4-bit quantization.
_QWEN_VRAM_GB_4BIT: float = 4.5
_QWEN_VRAM_GB_BF16: float = 15.0


# ---------------------------------------------------------------------------
# Parsing helpers (module-level, easily unit-tested)
# ---------------------------------------------------------------------------


def _parse_vlm_relevance(raw_output: str) -> tuple[float, str]:
    """Extract (relevance_score, reasoning) from the VLM's structured output.

    Expected format (case-insensitive)::

        RELEVANT: YES
        SCORE: 0.85
        REASONING: The image shows a woman in a red shirt near a coffee shop.

    Falls back to ``(0.5, raw_output)`` on any parse error so the pipeline
    never raises due to unexpected model phrasing.

    Args:
        raw_output: Raw text generated by Qwen2.5-VL.

    Returns:
        Tuple of ``(score_float, reasoning_string)``.
    """
    score: float = 0.5
    reasoning: str = raw_output.strip()

    lines = {
        line.split(":", 1)[0].strip().upper(): line.split(":", 1)[1].strip()
        for line in raw_output.splitlines()
        if ":" in line
    }

    try:
        raw_score = lines.get("SCORE", "")
        if raw_score:
            score = max(0.0, min(1.0, float(raw_score)))
    except ValueError:
        pass

    if "REASONING" in lines:
        reasoning = lines["REASONING"]
    elif "RELEVANT" in lines and lines["RELEVANT"].upper() == "NO":
        score = max(0.0, score - 0.2)

    return score, reasoning


# ---------------------------------------------------------------------------
# VLM Service
# ---------------------------------------------------------------------------


class VLMService:
    """Qwen2.5-VL inference service for VQA and System 2 deep reasoning.

    Lazy-loads the model on first use to avoid VRAM pressure at startup.
    All public methods are safe to call when the model is not loaded —
    they return empty/fallback values and log a warning.

    Example::

        vlm = VLMService(model_id="Qwen/Qwen2.5-VL-7B-Instruct", device="cuda")
        await vlm.load_model()
        answer = await vlm.extract_vqa_answer("What is she holding?", img_path)
        candidates = await vlm.deep_reason("query", top5, keyframes_dir)
    """

    def __init__(
        self,
        model_id: str = "Qwen/Qwen2.5-VL-7B-Instruct",
        device: str = "cuda",
        use_4bit: bool = True,
        max_vram_gb: float = 8.0,
        max_new_tokens: int = 256,
    ) -> None:
        """Initialise without loading weights.

        Args:
            model_id: HuggingFace model identifier.
            device: ``"cuda"`` or ``"cpu"``. Falls back to ``"cpu"`` when CUDA
                is unavailable.
            use_4bit: Load in 4-bit quantization (bitsandbytes) to reduce
                VRAM from ~15 GB to ~4.5 GB.  Ignored when ``device="cpu"``.
            max_vram_gb: Total VRAM ceiling for the entire process.  Used for
                the pre-load safety check.
            max_new_tokens: Maximum tokens to generate per inference call.
        """
        self._model_id = model_id
        self._device = device
        self._use_4bit = use_4bit
        self._max_vram_gb = max_vram_gb
        self._max_new_tokens = max_new_tokens

        self._processor: object | None = None
        self._model: object | None = None
        self._is_loaded: bool = False

    # ------------------------------------------------------------------
    # Public properties
    # ------------------------------------------------------------------

    @property
    def is_loaded(self) -> bool:
        """Whether the Qwen2.5-VL weights are resident in memory."""
        return self._is_loaded

    @property
    def device(self) -> str:
        """Effective compute device (may differ from requested if CUDA absent)."""
        return self._device

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def load_model(self) -> None:
        """Lazy-load Qwen2.5-VL processor and model weights.

        Uses 4-bit quantization by default (``use_4bit=True``) to stay
        within the 8 GB VRAM budget alongside Grounding DINO.

        Raises:
            VRAMOverflowError: If estimated model size exceeds ``max_vram_gb``.
            ModelNotLoadedError: If HuggingFace download or import fails.
        """
        if self._is_loaded:
            logger.info("[VLM] Model already loaded — skipping.")
            return

        try:
            import torch
            from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration
        except ImportError as exc:
            raise ModelNotLoadedError(self._model_id) from exc

        # ── CUDA availability check ──────────────────────────────────
        if self._device == "cuda" and not torch.cuda.is_available():
            logger.warning("[VLM] CUDA requested but unavailable — falling back to CPU.")
            self._device = "cpu"

        # ── VRAM guard ───────────────────────────────────────────────
        if self._device == "cuda":
            available_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
            estimated_gb = _QWEN_VRAM_GB_4BIT if self._use_4bit else _QWEN_VRAM_GB_BF16
            if estimated_gb > self._max_vram_gb or estimated_gb > available_gb:
                raise VRAMOverflowError(
                    required_gb=estimated_gb,
                    available_gb=min(available_gb, self._max_vram_gb),
                )

        logger.info(
            "[VLM] Loading %s on %s (4bit=%s) …",
            self._model_id, self._device, self._use_4bit,
        )
        try:
            processor = AutoProcessor.from_pretrained(
                self._model_id,
                trust_remote_code=True,
            )

            load_kwargs: dict[str, object] = {"trust_remote_code": True}
            if self._device == "cuda" and self._use_4bit:
                from transformers import BitsAndBytesConfig

                load_kwargs["quantization_config"] = BitsAndBytesConfig(
                    load_in_4bit=True,
                    bnb_4bit_compute_dtype=__import__("torch").bfloat16,
                )
                load_kwargs["device_map"] = "auto"
            else:
                load_kwargs["torch_dtype"] = "auto"

            model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
                self._model_id,
                **load_kwargs,
            )
            if "device_map" not in load_kwargs:
                model = model.to(self._device)
            model.eval()

        except Exception as exc:
            raise ModelNotLoadedError(self._model_id) from exc

        self._processor = processor
        self._model = model
        self._is_loaded = True
        logger.info("[VLM] Qwen2.5-VL loaded successfully on %s.", self._device)

    def unload_model(self) -> None:
        """Release model weights and free VRAM. Safe to call when not loaded."""
        if not self._is_loaded:
            return

        del self._model
        del self._processor
        self._model = None
        self._processor = None
        self._is_loaded = False

        try:
            import torch

            with contextlib.suppress(Exception):
                torch.cuda.empty_cache()
        except ImportError:
            pass

        logger.info("[VLM] Model unloaded and VRAM released.")

    # ------------------------------------------------------------------
    # Public inference methods
    # ------------------------------------------------------------------

    async def extract_vqa_answer(
        self,
        query: str,
        image_path: Path,
    ) -> str:
        """Run single-image VQA inference and return the answer string.

        Used for ``task_type="VQA"`` requests where the top reranked
        candidate must produce a text answer (e.g. "red shirt", "2").

        Falls back to an empty string when the model is not loaded or the
        image cannot be read.

        Args:
            query: The VQA question (e.g. "What is the person wearing?").
            image_path: Absolute path to the keyframe JPEG.

        Returns:
            Answer string, or ``""`` on failure / model absent.
        """
        if not self._is_loaded:
            logger.warning("[VLM] Model not loaded — returning empty VQA answer.")
            return ""

        image = _load_image(image_path)
        if image is None:
            return ""

        prompt = _VQA_PROMPT_TEMPLATE.format(query=query)
        return await self._generate(prompt, image)

    async def deep_reason(
        self,
        query: str,
        candidates: list[RerankResultItem],
        keyframes_dir: Path | str,
        top_k: int = 5,
    ) -> list[RerankResultItem]:
        """Apply System 2 CoT reasoning to the top-k candidates.

        For each of the top ``top_k`` candidates:
        1. Load the keyframe image.
        2. Prompt Qwen2.5-VL with the structured reasoning template.
        3. Parse the VLM response for ``(relevance_score, reasoning_trace)``.
        4. Blend the VLM score with the existing ``rerank_score``:
           ``final = 0.5 * rerank_score + 0.5 * vlm_score``
        5. Attach ``reasoning_trace`` to the result item.

        Candidates beyond ``top_k`` are returned unchanged.

        Falls back gracefully when the model is not loaded — all candidates
        are returned with ``reasoning_trace = None``.

        Args:
            query: Original search query.
            candidates: Already-sorted list from the grounding reranker.
            keyframes_dir: Root directory for keyframe images.
            top_k: Maximum number of candidates to apply VLM reasoning on.

        Returns:
            Full candidate list; first ``min(top_k, len(candidates))`` items
            have updated ``rerank_score`` and ``reasoning_trace``.
        """
        if not candidates:
            return []

        if not self._is_loaded:
            logger.warning(
                "[VLM] Model not loaded — skipping deep reasoning for %d candidates.",
                len(candidates),
            )
            return candidates

        reasoned: list[RerankResultItem] = []
        for candidate in candidates[:top_k]:
            image_path = _resolve_path(candidate.video_id, candidate.frame_id, keyframes_dir)
            image = _load_image(image_path)

            if image is None:
                # Can't load image — keep candidate unchanged.
                reasoned.append(candidate)
                continue

            prompt = _REASONING_PROMPT_TEMPLATE.format(query=query)
            raw_output = await self._generate(prompt, image)
            vlm_score, trace = _parse_vlm_relevance(raw_output)

            blended_score = 0.5 * candidate.rerank_score + 0.5 * vlm_score

            # Build a new item since RerankResultItem fields are immutable by default.
            reasoned.append(
                RerankResultItem(
                    video_id=candidate.video_id,
                    frame_id=candidate.frame_id,
                    original_score=candidate.original_score,
                    rerank_score=blended_score,
                    vqa_answer=candidate.vqa_answer,
                    grounding=candidate.grounding,
                    reasoning_trace=trace,
                )
            )

        # Re-sort the reasoned slice by the updated score.
        reasoned.sort(key=lambda r: r.rerank_score, reverse=True)

        # Append unmodified tail candidates.
        return reasoned + list(candidates[top_k:])

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _generate(self, prompt: str, image: "PIL.Image.Image") -> str:  # type: ignore[name-defined]
        """Run one Qwen2.5-VL forward pass and return the generated text.

        Args:
            prompt: Text prompt to send alongside the image.
            image: PIL RGB image.

        Returns:
            Generated text (stripped), or ``""`` on error.
        """
        try:
            # Build the chat-format messages list expected by Qwen2.5-VL.
            messages = [
                {
                    "role": "user",
                    "content": [
                        {"type": "image", "image": image},
                        {"type": "text", "text": prompt},
                    ],
                }
            ]

            text_input = self._processor.apply_chat_template(  # type: ignore[union-attr]
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
            inputs = self._processor(  # type: ignore[operator]
                text=[text_input],
                images=[image],
                return_tensors="pt",
                padding=True,
            ).to(self._device)

            # Use torch.no_grad() when available; fall back to contextlib.nullcontext
            # so unit tests with mock models work without PyTorch installed.
            try:
                import torch as _torch
                no_grad_ctx = _torch.no_grad()
            except ImportError:
                import contextlib as _cl
                no_grad_ctx = _cl.nullcontext()

            with no_grad_ctx:
                output_ids = self._model.generate(  # type: ignore[union-attr]
                    **inputs,
                    max_new_tokens=self._max_new_tokens,
                )

            # Strip the input tokens from the output.
            try:
                input_len = inputs["input_ids"].shape[1]
                generated_ids = [out[input_len:] for out in output_ids]
            except (KeyError, TypeError, AttributeError):
                # Mocked inputs may not have a real shape; decode directly.
                generated_ids = output_ids

            decoded = self._processor.batch_decode(  # type: ignore[union-attr]
                generated_ids,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False,
            )
            return decoded[0].strip() if decoded else ""

        except Exception as exc:  # noqa: BLE001
            logger.warning("[VLM] Inference failed: %s", exc)
            return ""


# ---------------------------------------------------------------------------
# Module-level helpers (pure, easily unit-tested)
# ---------------------------------------------------------------------------


def _resolve_path(video_id: str, frame_id: int, keyframes_dir: Path | str) -> Path:
    """Resolve the keyframe image path using the project convention.

    Delegates to the same convention as ``resolve_keyframe_path`` in
    ``reranker.py`` — defined locally here to avoid a circular import.
    Convention: ``{keyframes_dir}/{video_id}/{frame_id:06d}.jpg``
    """
    return Path(keyframes_dir) / video_id / f"{frame_id:06d}.jpg"


def _load_image(image_path: Path) -> "PIL.Image.Image | None":  # type: ignore[name-defined]
    """Load a JPEG keyframe into a PIL RGB image.

    Returns ``None`` (and logs a warning) on missing files or corrupt data.
    """
    if not image_path.exists():
        logger.warning("[VLM] Keyframe not found: %s", image_path)
        return None

    try:
        from PIL import Image, UnidentifiedImageError

        return Image.open(image_path).convert("RGB")
    except Exception as exc:  # noqa: BLE001
        logger.warning("[VLM] Cannot read keyframe %s: %s", image_path, exc)
        return None
